environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
version: 0.0.{build}
image:
    - Visual Studio 2017
    - Ubuntu
init:
    - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 70 --slave /usr/bin/g++ g++ /usr/bin/g++-8
before_build:
    - git submodule update --init --recursive
    - ps: Start-Process cmd -WorkingDirectory thirdparty/tinycc/win32 '/c "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" & build-tcc.bat -c cl -t 32 -i ..'
    - sh: ( cd thirdparty/tinycc ; ./configure ; make ; cd ../.. )
    - cmake .
build_script:
    - cmake --build . --config Release
artifacts:
    - path: bin
      name: artifacts
      type: zip